"""baseline schema

Revision ID: 944a49cd533d
Revises:
Create Date: 2026-07-05 17:42:19.339854

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "944a49cd533d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lego_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("set_number", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("theme", sa.String(length=120), nullable=True),
        sa.Column("subtheme", sa.String(length=120), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("retirement_year", sa.Integer(), nullable=True),
        sa.Column("piece_count", sa.Integer(), nullable=True),
        sa.Column("minifig_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "set_number = upper(trim(set_number))",
            name=op.f("ck_lego_sets_set_number_canonical"),
        ),
        sa.CheckConstraint(
            "minifig_count IS NULL OR minifig_count >= 0",
            name=op.f("ck_lego_sets_minifig_count_non_negative"),
        ),
        sa.CheckConstraint(
            "piece_count IS NULL OR piece_count >= 0",
            name=op.f("ck_lego_sets_piece_count_non_negative"),
        ),
        sa.CheckConstraint(
            "release_year IS NULL OR release_year BETWEEN 1949 AND 2100",
            name=op.f("ck_lego_sets_release_year_valid"),
        ),
        sa.CheckConstraint(
            "retirement_year IS NULL OR retirement_year BETWEEN release_year AND 2100",
            name=op.f("ck_lego_sets_retirement_year_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lego_sets")),
    )
    with op.batch_alter_table("lego_sets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lego_sets_set_number"), ["set_number"], unique=True
        )
        batch_op.create_index(
            "ix_lego_sets_theme_release_year", ["theme", "release_year"], unique=False
        )

    op.create_table(
        "marketplaces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("fee_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fee_percent >= 0 AND fee_percent <= 100",
            name=op.f("ck_marketplaces_fee_percent_valid"),
        ),
        sa.CheckConstraint(
            "name = lower(name)", name=op.f("ck_marketplaces_name_lowercase")
        ),
        sa.CheckConstraint(
            "name IN ('ebay', 'bricklink')",
            name=op.f("ck_marketplaces_name_allowed"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_marketplaces")),
    )
    with op.batch_alter_table("marketplaces", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_marketplaces_name"), ["name"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_users_username"), ["username"], unique=True
        )

    op.create_table(
        "marketplace_listings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lego_set_id", sa.Uuid(), nullable=False),
        sa.Column("marketplace_id", sa.Uuid(), nullable=False),
        sa.Column("external_listing_id", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("shipping_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("condition", sa.String(length=20), nullable=False),
        sa.Column("listing_status", sa.String(length=20), nullable=False),
        sa.Column("seller_name", sa.String(length=255), nullable=True),
        sa.Column("seller_rating", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("is_complete", sa.Boolean(), nullable=True),
        sa.Column("is_sealed", sa.Boolean(), nullable=True),
        sa.Column("match_confidence", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "condition IN ('new', 'used', 'unknown')",
            name=op.f("ck_marketplace_listings_condition_allowed"),
        ),
        sa.CheckConstraint(
            "listing_status IN ('active', 'sold', 'ended', 'removed')",
            name=op.f("ck_marketplace_listings_listing_status_allowed"),
        ),
        sa.CheckConstraint(
            "currency = upper(currency)",
            name=op.f("ck_marketplace_listings_currency_uppercase"),
        ),
        sa.CheckConstraint(
            "match_confidence IS NULL OR match_confidence BETWEEN 0 AND 100",
            name=op.f("ck_marketplace_listings_match_confidence_valid"),
        ),
        sa.CheckConstraint(
            "price >= 0", name=op.f("ck_marketplace_listings_price_non_negative")
        ),
        sa.CheckConstraint(
            "seller_rating IS NULL OR seller_rating BETWEEN 0 AND 100",
            name=op.f("ck_marketplace_listings_seller_rating_valid"),
        ),
        sa.CheckConstraint(
            "shipping_price >= 0",
            name=op.f("ck_marketplace_listings_shipping_price_non_negative"),
        ),
        sa.CheckConstraint(
            "total_price >= 0",
            name=op.f("ck_marketplace_listings_total_price_non_negative"),
        ),
        sa.CheckConstraint(
            "total_price = price + shipping_price",
            name=op.f("ck_marketplace_listings_total_price_matches_parts"),
        ),
        sa.ForeignKeyConstraint(
            ["lego_set_id"],
            ["lego_sets.id"],
            name=op.f("fk_marketplace_listings_lego_set_id_lego_sets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["marketplace_id"],
            ["marketplaces.id"],
            name=op.f("fk_marketplace_listings_marketplace_id_marketplaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_marketplace_listings")),
        sa.UniqueConstraint(
            "marketplace_id",
            "external_listing_id",
            name="uq_marketplace_listing_external_id",
        ),
    )
    with op.batch_alter_table("marketplace_listings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_marketplace_listings_marketplace_status_seen",
            ["marketplace_id", "listing_status", "last_seen_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_marketplace_listings_set_status_seen",
            ["lego_set_id", "listing_status", "last_seen_at"],
            unique=False,
        )

    op.create_table(
        "portfolio_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("set_number", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("purchase_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("condition", sa.String(length=20), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "condition IN ('new', 'used', 'sealed', 'unknown')",
            name=op.f("ck_portfolio_items_condition_allowed"),
        ),
        sa.CheckConstraint(
            "set_number = upper(trim(set_number))",
            name=op.f("ck_portfolio_items_set_number_canonical"),
        ),
        sa.CheckConstraint(
            "purchase_price >= 0",
            name=op.f("ck_portfolio_items_purchase_price_non_negative"),
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_portfolio_items_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["set_number"],
            ["lego_sets.set_number"],
            name=op.f("fk_portfolio_items_set_number_lego_sets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_portfolio_items_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_items")),
    )
    with op.batch_alter_table("portfolio_items", schema=None) as batch_op:
        batch_op.create_index(
            "ix_portfolio_items_set_number", ["set_number"], unique=False
        )
        batch_op.create_index("ix_portfolio_items_user_id", ["user_id"], unique=False)
        batch_op.create_index(
            "ix_portfolio_items_user_set", ["user_id", "set_number"], unique=False
        )

    op.create_table(
        "price_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lego_set_id", sa.Uuid(), nullable=False),
        sa.Column("marketplace_id", sa.Uuid(), nullable=False),
        sa.Column("condition", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("low_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("median_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("average_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("high_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "fair_market_value", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("listing_count", sa.Integer(), nullable=False),
        sa.Column(
            "source_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "snapshot_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "condition IN ('new', 'used', 'mixed', 'unknown')",
            name=op.f("ck_price_snapshots_condition_allowed"),
        ),
        sa.CheckConstraint(
            "average_price IS NULL OR average_price >= 0",
            name=op.f("ck_price_snapshots_average_price_non_negative"),
        ),
        sa.CheckConstraint(
            "currency = upper(currency)",
            name=op.f("ck_price_snapshots_currency_uppercase"),
        ),
        sa.CheckConstraint(
            "fair_market_value IS NULL OR fair_market_value >= 0",
            name=op.f("ck_price_snapshots_fair_market_value_non_negative"),
        ),
        sa.CheckConstraint(
            "high_price IS NULL OR high_price >= 0",
            name=op.f("ck_price_snapshots_high_price_non_negative"),
        ),
        sa.CheckConstraint(
            "listing_count >= 0",
            name=op.f("ck_price_snapshots_listing_count_non_negative"),
        ),
        sa.CheckConstraint(
            "low_price IS NULL OR high_price IS NULL OR low_price <= high_price",
            name=op.f("ck_price_snapshots_price_range_ordered"),
        ),
        sa.CheckConstraint(
            "low_price IS NULL OR median_price IS NULL OR low_price <= median_price",
            name=op.f("ck_price_snapshots_median_price_above_low"),
        ),
        sa.CheckConstraint(
            "high_price IS NULL OR median_price IS NULL OR median_price <= high_price",
            name=op.f("ck_price_snapshots_median_price_below_high"),
        ),
        sa.CheckConstraint(
            "low_price IS NULL OR average_price IS NULL OR low_price <= average_price",
            name=op.f("ck_price_snapshots_average_price_above_low"),
        ),
        sa.CheckConstraint(
            "high_price IS NULL OR average_price IS NULL OR average_price <= high_price",
            name=op.f("ck_price_snapshots_average_price_below_high"),
        ),
        sa.CheckConstraint(
            "low_price IS NULL OR fair_market_value IS NULL OR low_price <= fair_market_value",
            name=op.f("ck_price_snapshots_fair_market_value_above_low"),
        ),
        sa.CheckConstraint(
            "high_price IS NULL OR fair_market_value IS NULL OR fair_market_value <= high_price",
            name=op.f("ck_price_snapshots_fair_market_value_below_high"),
        ),
        sa.CheckConstraint(
            "low_price IS NULL OR low_price >= 0",
            name=op.f("ck_price_snapshots_low_price_non_negative"),
        ),
        sa.CheckConstraint(
            "median_price IS NULL OR median_price >= 0",
            name=op.f("ck_price_snapshots_median_price_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["lego_set_id"],
            ["lego_sets.id"],
            name=op.f("fk_price_snapshots_lego_set_id_lego_sets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["marketplace_id"],
            ["marketplaces.id"],
            name=op.f("fk_price_snapshots_marketplace_id_marketplaces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_snapshots")),
        sa.UniqueConstraint(
            "lego_set_id",
            "marketplace_id",
            "condition",
            "snapshot_at",
            name="uq_price_snapshot_market_condition_time",
        ),
    )
    with op.batch_alter_table("price_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_price_snapshots_set_snapshot_at",
            ["lego_set_id", "snapshot_at"],
            unique=False,
        )

    op.create_table(
        "recommendations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lego_set_id", sa.Uuid(), nullable=False),
        sa.Column("goal", sa.String(length=40), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("asking_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "fair_market_value", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column(
            "market_summary",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('BUY', 'PASS', 'SELL', 'HOLD', 'WATCH')",
            name=op.f("ck_recommendations_decision_allowed"),
        ),
        sa.CheckConstraint(
            "goal IN ('buy_set', 'sell_set', 'hold_vs_sell', 'buy_vs_pass')",
            name=op.f("ck_recommendations_goal_allowed"),
        ),
        sa.CheckConstraint(
            "asking_price IS NULL OR asking_price >= 0",
            name=op.f("ck_recommendations_asking_price_non_negative"),
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 100",
            name=op.f("ck_recommendations_confidence_score_valid"),
        ),
        sa.CheckConstraint(
            "fair_market_value IS NULL OR fair_market_value >= 0",
            name=op.f("ck_recommendations_fair_market_value_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["lego_set_id"],
            ["lego_sets.id"],
            name=op.f("fk_recommendations_lego_set_id_lego_sets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
    )
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_recommendations_set_goal_created",
            ["lego_set_id", "goal", "created_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.drop_index("ix_recommendations_set_goal_created")

    op.drop_table("recommendations")
    with op.batch_alter_table("price_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_price_snapshots_set_snapshot_at")

    op.drop_table("price_snapshots")
    with op.batch_alter_table("portfolio_items", schema=None) as batch_op:
        batch_op.drop_index("ix_portfolio_items_user_set")
        batch_op.drop_index("ix_portfolio_items_user_id")
        batch_op.drop_index("ix_portfolio_items_set_number")

    op.drop_table("portfolio_items")
    with op.batch_alter_table("marketplace_listings", schema=None) as batch_op:
        batch_op.drop_index("ix_marketplace_listings_set_status_seen")
        batch_op.drop_index("ix_marketplace_listings_marketplace_status_seen")

    op.drop_table("marketplace_listings")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("marketplaces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_marketplaces_name"))

    op.drop_table("marketplaces")
    with op.batch_alter_table("lego_sets", schema=None) as batch_op:
        batch_op.drop_index("ix_lego_sets_theme_release_year")
        batch_op.drop_index(batch_op.f("ix_lego_sets_set_number"))

    op.drop_table("lego_sets")
    # ### end Alembic commands ###
